title: Astronomy blog
author: slowe
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  A very seldom updated blog about astronomy.

# social links
twitter_username: astronomyblog # DO NOT include the @ character, or else the build will fail!
github_username:  slowe # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
